import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Ghani Bakery | Fresh & Handmade",
  description:
    "Roti, kue, dan pastry segar setiap hari. Pesan langsung via WhatsApp.",
  applicationName: "Ghani Bakery",
  keywords: [
    "bakery",
    "roti",
    "kue",
    "pastry",
    "donat",
    "croissant",
    "cake",
    "halal",
    "Gresik",
    "Bungah",
    "toko roti",
    "Bakery Gresik",
    "Roti Gresik",
    "Kue Gresik",
    "Pastry Gresik",
    "Roti Halal",
    "Kue Halal",
    "Pastry Halal",
    "Roti Segar",
    "Kue Segar",
    "Pastry Segar",
    "Roti Handmade",
    "Kue Handmade",
    "Pastry Handmade",
    "Roti Enak",
    "Kue Enak",
    "Pastry Enak",
    "Roti Murah",
    "Kue Murah",
    "Pastry Murah",
    "Roti Lezat",
    "Kue Lezat",
    "Pastry Lezat",
    "Roti Fresh",
    "Kue Fresh",
    "Pastry Fresh",
    "Ghani Bakery Gresik",
    "Ghani Bakery Bungah",
    "Ghani Bakery Roti",
    "Ghani Bakery Kue",
    "Ghani Bakery Pastry",
    "Ghani Bakery Donat",
    "Ghani Bakery Croissant",
    "Ghani Bakery Cake",
    "Ghani Bakery Halal",
    "Ghani Bakery Segar",
    "Ghani Bakery Handmade",
    "Ghani Bakery Enak",
    "Ghani Bakery Murah",
    "Ghani Bakery Lezat",
    "Ghani Bakery Fresh",
    "Pesan Roti Gresik",
    "Pesan Kue Gresik",
    "Pesan Pastry Gresik",
    "Pesan Roti Halal",
    "Pesan Kue Halal",
    "Pesan Pastry Halal",
    "Pesan Roti Segar",
    "Pesan Kue Segar",
    "Pesan Pastry Segar",
    "Pesan Roti Handmade",
    "Pesan Kue Handmade",
    "Pesan Pastry Handmade",
    "Pesan Roti Enak",
    "Pesan Kue Enak",
    "Pesan Pastry Enak",
    "Pesan Roti Murah",
    "Pesan Kue Murah",
    "Pesan Pastry Murah",
    "Pesan Roti Lezat",
    "Pesan Kue Lezat",
    "Pesan Pastry Lezat",
    "Pesan Roti Fresh",
    "Pesan Kue Fresh",
    "Pesan Pastry Fresh",
    "WhatsApp Roti Gresik",
    "WhatsApp Kue Gresik",
    "WhatsApp Pastry Gresik",
    "WhatsApp Roti Halal",
    "WhatsApp Kue Halal",
    "WhatsApp Pastry Halal",
    "WhatsApp Roti Segar",
    "WhatsApp Kue Segar",
    "WhatsApp Pastry Segar",
    "WhatsApp Roti Handmade",
    "WhatsApp Kue Handmade",
    "WhatsApp Pastry Handmade",
    "WhatsApp Roti Enak",
    "WhatsApp Kue Enak",
    "WhatsApp Pastry Enak",
    "WhatsApp Roti Murah",
    "WhatsApp Kue Murah",
    "WhatsApp Pastry Murah",
    "WhatsApp Roti Lezat",
    "WhatsApp Kue Lezat",
    "WhatsApp Pastry Lezat",
    "WhatsApp Roti Fresh",
    "WhatsApp Kue Fresh",
    "WhatsApp Pastry Fresh",
    "Order Roti Gresik",
    "Order Kue Gresik",
    "Order Pastry Gresik",
    "Order Roti Halal",
    "Order Kue Halal",
    "Order Pastry Halal",
    "Order Roti Segar",
    "Order Kue Segar",
    "Order Pastry Segar",
    "Order Roti Handmade",
    "Order Kue Handmade",
    "Order Pastry Handmade",
    "Order Roti Enak",
    "Order Kue Enak",
    "Order Pastry Enak",
    "Order Roti Murah",
    "Order Kue Murah",
    "Order Pastry Murah",
    "Order Roti Lezat",
    "Order Kue Lezat",
    "Order Pastry Lezat",
    "Order Roti Fresh",
    "Order Kue Fresh",
    "Order Pastry Fresh",
    "Toko Roti Gresik",
    "Toko Kue Gresik",
    "Toko Pastry Gresik",
    "Toko Roti Halal",
    "Toko Kue Halal",
    "Toko Pastry Halal",
    "Toko Roti Segar",
    "Toko Kue Segar",
    "Toko Pastry Segar",
    "Toko Roti Handmade",
    "Toko Kue Handmade",
    "Toko Pastry Handmade",
    "Toko Roti Enak",
    "Toko Kue Enak",
    "Toko Pastry Enak",
    "Toko Roti Murah",
    "Toko Kue Murah",
    "Toko Pastry Murah",
    "Toko Roti Lezat",
    "Toko Kue Lezat",
    "Toko Pastry Lezat",
    "Toko Roti Fresh",
    "Toko Kue Fresh",
    "Toko Pastry Fresh",
    "Ghani Bakery WhatsApp",
    "Ghani Bakery Order",
    "Ghani Bakery Toko Roti",
    "Ghani Bakery Toko Kue",
    "Ghani Bakery Toko Pastry",
    "Bakery Terdekat",
    "Roti Terdekat",
    "Kue Terdekat",
    "Pastry Terdekat",
    "Bakery Online",
    "Roti Online",
    "Kue Online",
    "Pastry Online",
    "Bakery Delivery",
    "Roti Delivery",
    "Kue Delivery",
    "Pastry Delivery",
    "Fresh Bakery",
    "Fresh Roti",
    "Fresh Kue",
    "Fresh Pastry",
    "Handmade Bakery",
    "Handmade Roti",
    "Handmade Kue",
    "Handmade Pastry",
    "Enak Bakery",
    "Enak Roti",
    "Enak Kue",
    "Enak Pastry",
    "Murah Bakery",
    "Murah Roti",
    "Murah Kue",
    "Murah Pastry",
    "Lezat Bakery",
    "Lezat Roti",
    "Lezat Kue",
    "Lezat Pastry",
  ],
  authors: [{ name: "Ghani Bakery", url: "/" }],
  creator: "Ghani Bakery",
  publisher: "Ghani Bakery",
  metadataBase: undefined,
  alternates: {
    canonical: "/",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-video-preview": -1,
      "max-image-preview": "large",
    },
  },
  openGraph: {
    title: "Ghani Bakery | Fresh & Handmade",
    description:
      "Roti, kue, dan pastry segar setiap hari. Pesan langsung via WhatsApp.",
    url: "/",
    siteName: "Ghani Bakery",
    images: [
      { url: "/logo-ghani.png", width: 512, height: 512, alt: "Logo Ghani Bakery" },
      { url: "/logo-ghani.svg", width: 512, height: 512, alt: "Logo Ghani Bakery SVG" },
    ],
    locale: "id_ID",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Ghani Bakery | Fresh & Handmade",
    description:
      "Roti, kue, dan pastry segar setiap hari. Pesan langsung via WhatsApp.",
    images: ["/logo-ghani.png", "/logo-ghani.svg"],
    creator: "@",
  },
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/favicon.ico",
  },
  viewport:
    "width=device-width, initial-scale=1, maximum-scale=5, viewport-fit=cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id">
      <head>
        <script
          type="application/ld+json"
          // eslint-disable-next-line react/no-danger
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Bakery",
              name: "Ghani Bakery",
              url: "/",
              email: "ghani.bakery@gmail.com",
              image: [
                "/logo-ghani.svg",
                "/bakery/hero-basket.svg",
              ],
              address: {
                "@type": "PostalAddress",
                streetAddress:
                  "Jl. Margo Mulyo, Karangjarak, Kisik, Kec. Bungah",
                addressLocality: "Kabupaten Gresik",
                addressRegion: "Jawa Timur",
                postalCode: "61152",
                addressCountry: "ID",
              },
              geo: {
                "@type": "GeoCoordinates",
                latitude: -7.034470892967442,
                longitude: 112.57501507505638,
              },
              servesCuisine: "Bakery",
              priceRange: "IDR",
            }),
          }}
        />
        <meta name="theme-color" content="#ffffff" />
      </head>
      <body className={`antialiased bg-background text-foreground`}>
        {children}
      </body>
    </html>
  );
}
